--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/MakePluginPlus-PMMP/MakePluginPlus

branches:
- master

projects:
  MakePluginPlus:
    projectId: 2889
    path: ""
    icon: assets/icon/512x512.png
...