---
name: BluginTools
main: blugin\tool\dev\BluginTools
version: 2.1.0
api: [3.0.0]
authors: ['Blugin-team', 'PresentKim']
description: '[tool] Several tools to help with pmmp plugin development'
depend: ['DevTools', 'libTranslator']

commands:
  bluginbuilder:
    description: Build plugin with more option
    usage: /bluginbuilder <plugin name | *>
    aliases: [build, bb]
    permission: bluginbuilder.cmd

permissions:
  bluginbuilder.cmd:
    description: 'Build plugin with more option'
    default: op
...
