---
name: MakePluginPlus
main: blugin\makepluginplus\MakePluginPlus
version: 1.1.0
api: [4.0.0]
author: PresentKim
description: Make plugin with more option (more optimize)
depend: ['DevTools']

permissions:
  makepluginplus.cmd:
    description: MakePluginPlus main command
    default: op
...
