---
name: BluginBuilder
main: blugin\tool\builder\BluginBuilder
version: 0.0.1
api: [3.0.0, 4.0.0]
authors: ['Blugin-team', 'PresentKim']
description: '[tool] Plugin builder plugin for Blugin-team'
depend: ['DevTools', 'libPhpParser']

commands:
  bluginbuilder:
    description: Plugin builder with more option
    usage: /bluginbuilder <plugin name | *>
    aliases: [build, bb]
    permission: bluginbuilder.cmd

permissions:
  bluginbuilder.cmd:
    description: '[BluginBuilder] Build folder plugin with mre option'
    default: op
...
