---
preprocessing:
  variable-renaming: protect
  minor-optimizating: true
  comment-optimizing: true
  resolve-importing: true

build:
  print-format: shorten
  include-minimal: true
  skip-metadata: true
  skip-stub: true
...